---
- name: Download na unarchive
  unarchive:
    src: "{{ item.url }}"
    dest: /tmp/
    remote_src: yes
  with_items:
    - "{{ items }}"

- name: Copy node_exporter binary
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin
    remote_src: yes
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    

- name: Propagate prometheus/promtool binaries
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: '0755'
  with_items:
    - prometheus
    - promtool

- name: Move Prometheus console* files
  shell:
    cmd: cp -R /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }} /etc/prometheus/
  with_items:
    - consoles
    - console_libraries

- name: Copy prometheus.yml
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0744'

- name: Copy .service
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '0744'
  with_items:
    - prometheus.service
    - node_exporter.service

- name: restart prometheus/node_exporter services
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - prometheus.service
    - node_exporter.service