---
- name: Install webhook
  apt:
    name: webhook
    state: latest

- name: Slurp secret
  slurp:
    src: /var/webhook_secret
  register: secret

- name: Generate hooks.json
  template:
    src: hooks.json
    dest: /etc/webhook/hooks.json
    owner: webhook
    group: webhook
    mode: '0644'

- name: Copy webhook.service
  copy:
    src: webhook.service
    dest: /etc/systemd/system/webhook.service
    owner: root
    group: root
    mode: '0744'
  notify: restart webhook

