---
- name: Install firewall software
  apt:
    name: ['nftables']
    state: 'present'
    update_cache: true

- name: Copy nftables config
  copy:
    src: 'nftables.conf'
    dest: '/etc/nftables.conf'
    owner: 'root'
    group: 'root'
    mode: '0755'
    backup: true
