---
items:
  - version: "{{ prometheus_version }}"
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    name: prometheus
  - version: "{{ node_exporter_version }}"
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    name: node_exporter
# prometheus_items: ["{{ prometheus_url }}", prometheus]
# node_exporter_items: ["{{ node_exporter_url }}", node_exporter]

# https://github.com/prometheus/prometheus/releases/download/v2.27.1/prometheus-2.27.1.linux-amd64.tar.gz
# https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
