---
- name: Install libfontconfig1
  apt:
    name: libfontconfig1
    state: latest

- name: Install a .deb package from the internet
  apt:
    deb: "{{ grafana_url }}"

- name: Copy nginx.conf
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0640'
  notify: restart grafana