---
- name: Provision infrastructure to automatic deployment site
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - common
    - webhook
    - nginx
    - deployment
    