baseURL = "https://dobrosielski.icu"
title = "Julian Dobrosielski"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Junior DevOps candidate"
  copyright = "Copyright © 2021 Julian Dobrosielski"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "CV_eng"
    name = "CV_eng"
    title = "CV_eng"
    url = "/cv_eng.pdf"
    weight = 20
  [[menu.main]]
    identifier = "CV_pol"
    name = "CV_pol"
    title = "CV_pol"
    url = "/cv_pol.pdf"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
