name: Deploy

on:
  push:
    branches: [ nomad ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: klakegg/hugo:0.83.1-ci
    steps:
      - uses: actions/checkout@v2
      - name: Build artifact
        run: cd src && hugo
      - name: Store artifact for deploy
        uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: src/public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site-artifact
      - name: Deploy to server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /var/www/html/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}



