name: Deploy
# TODO: change script xargs in specific positon to only restart nginx task
# docker build --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t mytool:latest .
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: cd src && hugo --minify

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/
          platforms: linux/amd64
          push: true
          tags: ghcr.io/mich4n/site:latest

  trigger:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger nomad
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: /home/SVC-gha/restart.sh
